### PR TITLE
code review-jt

### PR DESCRIPTION
**Pull request by tranjg**

### CODE REVIEW

**Comment by tranjg** [comment]
https://github.com/Yep-Was-Taken/pupBuddy/pull/28/commits/df743ecf11172231fd63bfcfd3670a7da7d36355

I created a new templates folder in hopes that the application is able to read the HTML files, but I think there is a dependency issue that's preventing the HTML files to be recognized.

**Comment by tranjg** [comment]
https://github.com/Yep-Was-Taken/pupBuddy/pull/28/commits/b2dbc04757d76e44a85503848a690516ed88993e

I changed the name of a variable so that it matches the naming conventions, making sure the variables are consistent and easy to recognize.

**Comment by tranjg** [comment]
https://github.com/Yep-Was-Taken/pupBuddy/pull/28/commits/e03fcb93ff9dbe58bc209b32fef7c19ce6a87426

I changed the view into one of the HTML files you've created, but there is an error where the MVC view can't reach the file specified. I believe this might have to do with the dependicies.

**Comment by tranjg** [comment]
Overall, I've learned from this project 
1. To make sure that the dependencies are working as they should so that there aren't any errors.
2. When creating DTO to make sure that the model represents the business logic well, in other words, that the model has use within the system.
3. A new library called lombok where it automatically creates constructors for you.

**Comment by discospiff** [comment]
This group needs to submit a URL for their Android repository.  This is the Spring Boot repository.  Thus... not applicable to this class.

**Pull request closed without merging**
